name: 🤖 Request a new command
description: Suggest an command for this project
title: "[New Command]: /<command category> [command_group] <command_name> "
labels: ["enhancement", "new-command"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! We will use `/manage credits give` as an example for our placeholders.
  - type: input
    id: category
    attributes:
      label: Category
      description: Where should we put this command?
      placeholder: ex. manage
    validations:
      required: true
  - type: input
    id: group
    attributes:
      label: Group
      description: Does this command belong to this group?
      placeholder: ex. credits
  - type: input
    id: command
    attributes:
      label: Command
      description: What should we call this command?
      placeholder: ex. give
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What should the command do?
      description: Please tell us your concept, how it should work, and if there should be any additional features.
      placeholder: "I would like to have a command to give users credits, that would make it easier for me to administrate credits! I would like it to add a specified amount of credits to specified user, without taking credits from the executer. Command should require Manage Guild permission. When successful, it should return something like: Added <amount> credits to <user>!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
